apiVersion: v1
kind: Secret
metadata:
  name: ghost-registry-secret
  namespace: project-ghost-registry
type: Opaque
stringData:
  # Generate with: openssl rand -hex 32
  REGISTRY_API_KEY: "CHANGE_ME"
