apiVersion: v1
kind: Secret
metadata:
  name: ghost-deployments-secret
  namespace: project-ghost-deployments
type: Opaque
stringData:
  # Generate with: openssl rand -hex 64
  JWT_SECRET: "CHANGE_ME"
  S3_ACCESS_KEY: "CHANGE_ME"
  S3_SECRET_KEY: "CHANGE_ME"
